steps:
  - id: go_test
    name: "gcr.io/cloud-builders/go"
    args: ["test", "hpa"]
    env: ["GOPATH=go/."]

  - id: "Building image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "version=0.0.1",
        "-t",
        "gcr.io/$PROJECT_ID/go-hpa:latest",
        "./go",
      ]
images:
  - "gcr.io/$PROJECT_ID/go-hpa:latest"
